import { DifferentialDiagnosis } from '../../types/clinical';
import { GuidelinePassage } from '../../types/agent';
import { toolRegistry } from '../tools';

/**
 * Node 6: Grounding Safety Validator & AST Guardrail.
 * Audits every citation generated by Node 5 against UnifiedKnowledgeBase.
 */
export async function executeNode6_SafetyValidator(
  differentials: readonly DifferentialDiagnosis[],
  retrievedGuidelines: readonly GuidelinePassage[]
): Promise<{
  isGrounded: boolean;
  verifiedCitationIds: string[];
  redactedClaims: string[];
}> {
  const validIds = new Set(retrievedGuidelines.map(g => g.citationId));
  const verifiedCitationIds: string[] = [];
  const redactedClaims: string[] = [];

  for (const diff of differentials) {
    for (const id of diff.citationIds) {
      if (validIds.has(id)) {
        if (!verifiedCitationIds.includes(id)) {
          verifiedCitationIds.push(id);
        }
      } else {
        redactedClaims.push(`Redacted ungrounded citation '${id}' in condition '${diff.conditionName}'.`);
      }
    }
  }

  // Export FHIR Triage Audit Log via Local Agent Tool
  await toolRegistry.executeTool('tool_export_fhir_triage_log', {});

  return {
    isGrounded: redactedClaims.length === 0,
    verifiedCitationIds,
    redactedClaims
  };
}
